export const theme = {
  COLORS: {
    RED_BUTTON: '#F8375D',
    OPACITY_BUTTON: '#c62c4a',
    BACKGROUND: '#191920',
    WHITE: '#FFF',
    BLACK: '#000000',
    ITEM_TITLE: '#333',
    GRAY: '#999',
    BACKGROUND_HEADER: '#141419',
    CARD_SUMMARY: '#EEE',
    BORDER_INPUT: '#DDD'
  },

  FONTS: {
    ROBOTO: 'ROBOTO',
    ROBOTO_BOLD: 'ROBOTO_BOLD',
    ROBOTO_BLACK: 'ROBOTO_BLACK',
    ROBOTO_LIGHT: 'ROBOTO_LIGHT'
  }
}
